import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import SubNavigation from "@/components/subnavigation";
import SubNavigationDesktop from "@/components/subnavigationdesktop";
import Header from "@/components/header";
import { ThemeProvider } from "@/components/themeprovider/theme-provider";

const figtree = Figtree({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body
        className={`${figtree.className} antialiased`}
        suppressHydrationWarning
      >
        <div className="relative flex flex-col min-h-screen">
          <ThemeProvider attribute="class" disableTransitionOnChange>
            <SubNavigation />
            <SubNavigationDesktop />
            <Header />
            {children}
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
